[INFO:] Activating virtual env
[INFO:] DATA FOLDER: /home/ubuntu/DataEngineering_Jobs_Data_ETL_Pipeline/data
[INFO:] SCRIPT FILE: /home/ubuntu/DataEngineering_Jobs_Data_ETL_Pipeline/script/run.sh
[INFO:] LOG FILE FOR run.sh IS AT: /home/ubuntu/DataEngineering_Jobs_Data_ETL_Pipeline/logs/run.sh_19-11-2024-19-54-07.log
[INFO:] PYTHON FILE: /home/ubuntu/DataEngineering_Jobs_Data_ETL_Pipeline/script/run.py
[INFO:] LOG FILE FOR run.py IS AT: /home/ubuntu/DataEngineering_Jobs_Data_ETL_Pipeline/logs/run.py_19-11-2024-19-54-07.log
[DEBUG:] PYTHON_FILE is set to: /home/ubuntu/DataEngineering_Jobs_Data_ETL_Pipeline/script/run.py
[INFO:] RUNNING PYTHON SCRIPT /home/ubuntu/DataEngineering_Jobs_Data_ETL_Pipeline/script/run.py
The shape of the downloaded data is : (20, 5)
The columns in the downloaded data is Index(['company.name', 'locations', 'name', 'type', 'publication_date'], dtype='object')
Data is extracted!
The shape of the dataset is : (20, 5)
The columns in the dataset are: Index(['company.name', 'locations', 'name', 'type', 'publication_date'], dtype='object')
Traceback (most recent call last):
  File "/home/ubuntu/DataEngineering_Jobs_Data_ETL_Pipeline/script/run.py", line 118, in <module>
    main()
  File "/home/ubuntu/DataEngineering_Jobs_Data_ETL_Pipeline/script/run.py", line 102, in main
    save_data(df, '../data/data_raw.csv')
  File "/home/ubuntu/DataEngineering_Jobs_Data_ETL_Pipeline/script/run.py", line 64, in save_data
    df.to_csv(file_name, encoding='utf-8-sig', index=False) # otherwise it writes row numbers as a column
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/DataEngineering_Jobs_Data_ETL_Pipeline/.v_env/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/DataEngineering_Jobs_Data_ETL_Pipeline/.v_env/lib/python3.12/site-packages/pandas/core/generic.py", line 3967, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/DataEngineering_Jobs_Data_ETL_Pipeline/.v_env/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/ubuntu/DataEngineering_Jobs_Data_ETL_Pipeline/.v_env/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/ubuntu/DataEngineering_Jobs_Data_ETL_Pipeline/.v_env/lib/python3.12/site-packages/pandas/io/common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "/home/ubuntu/DataEngineering_Jobs_Data_ETL_Pipeline/.v_env/lib/python3.12/site-packages/pandas/io/common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '../data'
[ERROR:] Failed to execute Python script.
